### ISSUE TITLE
How to make the server interpret any file as PHP?

### ISSUE THREAD

**Issue by gyorokpeter** [FlashpointProject/Flashpoint-Router#4]
I'm trying to curate a collection of games from a site where each game uses a common "loader" swf that gets passed some GET parameters, and that loads another SWF as well as a string resource file from a URL that has a ".pet" extension and itself takes GET parameters and returns different content based on them. I tried to create a file with that name containing a PHP script that would redirect to other files based on the GET parameters, however the server just returns the PHP code rather than executing it.

**Comment by tomysshadow** [comment]
Your issue is the same as the previous. The Router always serves files in
htdocs statically. Any scripts need to be in the cgi-bin folder.

**Comment by gyorokpeter** [comment]
And if I'm making a curation, how do I specify which file goes into cgi-bin and which file goes into htdocs?

**Comment by tomysshadow** [comment]
There is no automatic method as of right now. You need to make an Author
Note in your curation.

**Comment by tomysshadow** [comment]
It's worth mentioning that long term the Flashpoint Router is going to be
replaced entirely by Game ZIPs which will negate this issue.

**Comment by gyorokpeter** [comment]
Some other questions on this topic:
- is there a way to print some text on the logs from the PHP file for debugging purposes?
- is there a way to view the logs of the server other than switching to the logs tab in Flashpoint? Switching tabs is inconvenient because then I have to switch back to the curations tab to launch the swf again, and doing that resets both the selected curation and the scroll within the page.

**Comment by tomysshadow** [comment]
The Launcher looks for log messages on stdout and stderr. So yes you can
write log messages from your PHP script, by calling fopen/fclose with
php://stderr.

There isn't a way to pop logs out into a different window that I know of -
that's more of a feature that you should be suggesting to the Launcher
developers.
